# TODO:
# 1000 - 1530

# DONE:



#
# Created 21.04.08, Cvet
#
# В данном файле сценаристы могут создавать свои строки.
#


{10}{}{Test0}
{11}{}{Test1}
{12}{}{Test2}
{13}{}{Test3}

#
# Nuka-Cola machine
#
{100}{}{You see a Nuka-Cola machine. You wonder if it still works.}
{101}{}{[thunk thunk chaching... sheeew]}
{102}{}{You get a not so fresh bottle of Nuka-Cola.}
{103}{}{Dooohhhh!}
{104}{}{You dodge the can of Nuka-Cola.}
{105}{}{@lex name @ skillfully dodges a can of Nuka-Cola.}
{106}{}{The machine seems to be out of stock.}


#
# Sandbag. Barricades stuff.
#
{200}{}{Мешок порвался у вас в руках - его нельзя класть в этом месте.}
{201}{}{В этом месте больше невозможно уложить ни одного мешка. }
{202}{}{Вы развязали мешок и высыпали песок из него на землю.}

#
# Extended craft.
#
{300}{}{Для производства требуется находиться рядом со cпециальным станком или верстаком.}
{301}{}{Станок или верстак в неработоспособном состоянии. Производство невозможно. Попробуйте позже.}
{302}{}{Станок или верстак в неработоспособном состоянии. Произведен максимум возможных предметов. Производство невозможно.}

#
# Generic messages
#

{500}{}{Gets @lex result@ on a die roll} # Dice
{510}{}{Yes} # Magic ball
{511}{}{No} # Magic ball
{520}{}{Preens @sex@|him||her|self} # Cosmetic
{530}{}{. Puffs on a cig .oO} # Cigarettes

#
# Guarded item
#

{540}{}{Отойди оттуда, @lex pname@}
{540}{}{Не вынуждай меня применить оружие, @lex pname@}
{540}{}{Эй, @lex pname@! Чем это ты занимаешься? Убирайся}
{540}{}{Не трогай это, @lex pname@}
{540}{}{@lex pname@! Немедленно перестань}

#
# Den store house
#

{1000}{}{Next!}
{1001}{}{Hey you! Do not approach!}
{1002}{}{Your time is coming to an end! If you don't hurry up I'll order the guard to kill you.}
{1003}{}{Guard}
{1004}{}{Эй, ты чего там делаешь?@@Сдохни, ворюга@@C ворами у меня разговор короткий@@Ребята, смотрите-ка, у нас воришка объявился@@Сейчас руки-то тебе поотрываю@@Вконец обнаглели. Посреди бела дня. В банке@@Очистим банки от ворья}

#
# Den entrance messages
#

{1050}{}{Вы испытываете странное чувство полной разрухи.}
{1051}{}{Где-то в глубине души вы очень рады, что покинули это место.}

#
# Den Bar Bekky boy
#

{1101}{}{Hmm...}
{1101}{}{Radio! Buy a radio!}
{1102}{}{La la la.}

#
# Quest warehouse
#

{1200}{}{Turrets on.}
{1201}{}{Turrets off.}
{1205}{}{Beep-Beep.}

#
# Den bank
#

{1300}{}{Get him, boys!}

#
# Den Trigger
#

{1400}{}{Something has crackled underfoot.}

#
# Manufacture, Alcohol
#

# Use
{1500}{}{The distillation device is out of order.}
{1501}{}{Firewood needed.}
{1502}{}{You watch as the firewood burns in the stove.}
{1503}{}{There is a fresh-brewed beer in a tank!}
{1504}{}{The tank with home-distilled alcohol is brimmed!}
# Use empty bottles
{1505}{}{You poured beer into the bottles.}
{1506}{}{You poured alcohol into the bottles.}
{1507}{}{You don't have enough bottles.}
# Use firewood
{1508}{}{This device is broken.}
{1509}{}{Need more firewood. What you have is probably not enough.}
{1510}{}{You don't know what ingredients to use and what the poportions are.}
{1511}{}{You prepared and poured in the stuff. You lit a fire in the stove. Distillation has begun.}
{1512}{}{You lit a fire in the stove and poured in the stuff. Home-distillated vodka is filling the tank.}
{1513}{}{There is enough wood there already.} 
{1514}{}{At first you have to pour out brewed beer.}
{1515}{}{At first you have to pour out distilled vodka.}
# To broke
{1516}{}{You have just broken the brewerage device.}
{1517}{}{You have just broken the distillating device.} 
{1518}{}{The boiler did not withstand the pressure and exploded!}
{1519}{}{Your eyes were splattered with boiling water.}
# Repair
{1520}{}{Looks like you need some details.}
{1521}{}{You need tools to fix this.}
{1522}{}{You have succesfully fixed the device.}
{1523}{}{You have failed at repairing and broken some details.}
# Science
{1524}{}{Device can be adjusted, but you need a wrench or something like that.}
{1525}{}{You broke your wrench. As well as the device.}
{1526}{}{During adjustment you dismounted half of the device. Now you need to assemble it back somehow.}
{1527}{}{You adjusted something carefully but it was useless.}
{1528}{}{You have adjusted the brewerage device. Now you'll need much less firewood.}
{1529}{}{You have adjusted the distillation device. Now you'll need much less firewood.}
{1530}{}{You have failed to adjust the device. Luckily, nothing got broken.}
# Scenery
{1560}{}{Some cereals lay here. They are cleansed and dried.}
{1561}{}{Fermentation of raw materials for alcohol takes place in these tanks.}

#
# Casino
#

{2000}{}{*Ring-a-ling*}
{2000}{}{*Zzzzzzz*}
{2000}{}{*Bing*}
{2000}{}{*Dingity-ding*}
{2000}{}{*Ding*}
{2000}{}{*Kaa-ching*}
{2001}{}{The machine is out of money.}

#
# Car, car.fos
#

{2100}{}{Number: @lex number@. Fuel: @lex fuel@/@lex fuel_tank@. Damage: @lex wear@%.}

#
# Getting firewood from tree (use axe on tree)
#

{2200}{}{This is suitable tree. You could cut fide wood... if your hands were okay.}
{2201}{}{You need to rest.}
{2202}{}{You hit your hand instead of tree!}
{2203}{}{You've cut some fire wood.}
{2204}{}{You've cut some fire wood, but can't carry it all.}
{2205}{}{You've cut some fire wood, but can't carry it at all.}

#
# Rangers
#

{2300}{}{Your target was liquidated by another ranger. Return to the outpost to get a new assignment.}

#
# Klamath, Bathhouse
#

{2400}{}{You didn't manage to figure out how to repair the pipe.}
{2401}{}{Farewell, babe.}
{2402}{}{Come back sometime.}
{2403}{}{I'll miss you.}
{2404}{}{You know where to find me.}

#
# Klamath, Grazing Area, Dogs. Using in klam_cowboy.fos
#

{2500}{}{Woooof! Woof! Woof!}
{2501}{}{Grrrrr!}
{2502}{}{Grr! Woof!}
{2503}{}{Woof!}
{2504}{}{Woof! Woof!}
{2505}{}{Woof! Woof! Wooof!}
{2506}{}{Wooooof!}
{2507}{}{*whines*}

#
# Primal tribe. Using in quest_trib_raiders_attack.fos
#
{2600}{}{Our tribe's Chief wants to talk to you.}
{2600}{}{Talk to Sulik.}
{2600}{}{The Chief is awaiting you.}
{2600}{}{Thanks for your help. Talk to the Chief.}
{2600}{}{The Chief wants to see you.}

#
# Slavers hunting. Using in q_slavers_hunt.fos
#
{2700}{}{Slavers base.}
{2701}{}{Вы сверяетесь с картой Элизы.\nСкорее всего работорговцев нужно искать между Кламатом и Ямой.}

#
# Dappo's lost caravan/ Using in q_dappo_lost_c_robot.fos
#
{2800}{}{Useless. I have find something else...}
{2801}{}{Hmmm... I can copy record from his camera.}
{2802}{}{Enemy spotted!}
{2803}{}{Enemy killed}
{2804}{}{Control point reached.}
{2805}{}{Moving next point...}
{2806}{}{От каравана Даппо мало что осталось. Пресловутым грузом оказался боевой робот в заводской упаковке.}
{2807}{}{Очевидно, что робот случайно активировался, выбрался на свободу и уничтожил караван. Даппо должен узнать, что произошло с его людьми. Робот не пожалел никого.}

#
# Alex holodisk. Using in q_ncr_alex_holo.fos
#
{2900}{}{Кажется, это то самое место, о котором говорится в голодиске. Осталось найти ящик.}
{2901}{}{Это место не похоже на то, что указано в голодиске.}

#
# NCR Michael. Using in ncr_michael.fos
#
{2910}{}{Посмотрим, что изменилось в Республике...}
{2911}{}{Бог ты мой, это же Майкл! Майкл, какими судьбами?}
{2912}{}{Отставить базар! Ему разрешено пройти.}

#
# NCR Westin. Using in ncr_westin.fos
#

{2930}{}{Тяжелый день...}
{2931}{}{Ну вот, опять нужно куда-то идти...}

#
# NCR Siege. Using in ncr_siege.fos
#

{2940}{}{Внимание! Говорит командир Рейнджеров НКР Элиза. Рейнджерам Республики нужна ваша помощь. Подступы к столице оккупированы бандами рейдеров и работорговцев. Мы платим за каждый вырезанный лагерь. Подробности у сержанта Кайла. Конец связи.}
{2941}{}{Внимание! Говорит командир Рейнджеров НКР Элиза. От имени штаба Армии НКР объявляю благодарность всем, оказавшим помощь. Рейдеры ликвидированы. Повторяю. Рейдеры уничтожены. Конец связи.}
{2942}{}{Это один из лагерей бандитов, угрожающих безопасности НКР.@@Вы нашли одно из мест, где закрепились рейдеры перед рещающей атакой на НКР.@@Здесь собрались самые отчаянные головорезы Пустоши. Они блокируют выходы из столицы Республики, убивают патрульных рейнджеров и грабят караваны НКР.}

#
# NCR Invasion. Using in ncr_invasion.fos
#
{2950}{}{Жалкие твари. Вы все подохнете как крысы@@Рейнджеры - пи*кашляет*!!!@@Сдохните, жалкие твари!@@НКР будет нашим! Мы наведем здесь порядок!@@Пацаны, смотрите, еще один. Вали его!@@Затопим эту дыру кровью рейнджеров!@@Вы все сдохнете!@@Убивайте всех. Не жалейте ни женщин ни детей.@@Республика падет!@@Мочи! Круши! Убей!@@Эй! НКР! Вы все должны сдохнуть!@@Ха-ха-ха!@@Умри!@@C дороги, мясо}
{2951}{}{Внимание! Всем! Всем! Говорит командир Рейнджеров НКР Элиза. На столицу Республики совершено нападение. Центр города пока в безопасности. Но на Базаре ситуация плачевная. Рейдеры закрепились на входе в город. Прорывайтесь в центр города для координации действий. Конец связи.}

#
# NCR Diplomatic mission. Using in ncr_shaiman.fos
#
{2960}{}{Вы не сумели взломать кейс c официальным ответом Братства Стали для генерала Армии НКР Шеймана.}
{2961}{}{Вы взломали замки кейса и прочитали письмо паладинов. Текст письма записан в вашем архиве.}

#
# Hell. Using in map_hell_level1.fos
#
{3000}{}{Как оказалось, трос не достает до земли, и вы, оценив расстояние до неё, решили прыгнуть вниз.}
{3001}{}{Вы не слишком удачно приземлились, сломав обе ноги.}
{3002}{}{Вы не слишком удачно приземлились, сломав левую ногу.}
{3003}{}{Вы не слишком удачно приземлились, сломав правую ногу.}
{3004}{}{Приземление, хоть и оказалось жестким, обошлось для вас лишь парой синяков и ушибов.}
{3005}{}{Вы не слишком удачно приземлились головой вниз.}
{3006}{}{A-A-A-A!!!}

#
# Hell. Using in hell_pipboys.fos
#
{3020}{}{Вы допущены до работы по сборке пипбоев. Когда решите выйти отсюда, привлеките внимание надзирателя.}
{3021}{}{You assembled a Pip-Boy. Total assembled: @lex pipnum@}
{3022}{}{You earned @lex sum@ dollars.}
{3023}{}{You earned @lex sum@ coins. Money were transferred to your replication account. Your balance is equal to: @lex bill@ dollars.}
{3024}{}{Congratulations! You have cleared your replication debt. You can now leave the special replication station.}
{3025}{}{У вас нет инструментов, необходимых для работы.}
{3026}{}{Вы исчерпали месячный лимит на оплату репликационных работ наличными.}

#
# Hell. Using in hell_mine_ore_reception.fos
#
{3030}{}{Терминал для сдачи добытой руды. Вы заглядываете в проем в стене, но ничего интересного там не видите. Оттуда лишь исходит странный гул, идущий откуда-то снизу.}

#
# Hell. Using in hell_mine_mining.fos
#
{3035}{}{Вы откололи кусок руды, который кажется более увесистым, чем остальные.@@Похоже, попалось то, что нужно.@@Вам попадается кусок породы с красивыми белыми прожилками.@@Кусок отличной породы глухо падает на пол.@@Вам попадается довольно неплохой кусок породы.}
{3036}{}{Вам попалась только пустая порода. Опять не везёт!@@Вы не добыли ничего полезного.@@Вы откалываете несколько крупных булыжников, но после осмотра понимаете, что это простой гранит.@@Вы усиленно колотите породу кувалдой, но ничего путного не попадается.}
{3037}{}{Вы откололи кусок руды, который кажется более увесистым, чем остальные.@@Похоже, попалось то, что нужно.@@Вам попадается кусок руды с золотой прожилкой.@@Отличный золотой самородок глухо падает на пол.@@Вам попадается довольно неплохой кусок породы.}


#
# Hell. Using in hell_lumbering.fos
#
{3040}{}{Вы допущены до работы на лесоповале. Когда решите выйти отсюда, обратитесь к солдату охраны.}
{3041}{}{Чтобы сдать дрова и получить награду, обратитесь к хабологам в соседнем здании.}

#
# Hell. Using in hell_level3.fos
#
{3045}{}{Вы не видите причин для того, чтобы лезть в эту странную дыру.}
{3046}{}{Вам не удаётся починить генератор. Попробуйте на свежую голову.}
{3047}{}{Покопавшись в генераторе, вы находите пару порваных проводов и быстро устраняете проблему.}

 #
 # Доска объявлений в НКР using in ncr_common.fos
 # ** КУПЛЮ ** 3100..3109
{3100}{}{СРОЧНО куплю Джет... и Баффаут. Доктор Трой.}
{3101}{}{Куплю патроны к солнечному скорчеру за любую цену. Избранный}
{3102}{}{Куплю силовую броню, 94 размера (Обращаться к Маркусу, шерифу Броукен Хиллз)}
{3103}{}{Куплю телевизоры, холодильники, радио-ДОРОГО. Вик}
{3104}{}{Куплю удобрение, желательно не вызывающее появление перхоти. Гарольд}
{3105}{}{Купим железную муху и железных людей. Дети Райт. Заплатит папа (наверное). }
{3106}{}{Куплю контактные линзы -3,5 на оба глаза, продам скобки для зубов, бу (обращаться в Главный Офис Ваут-Сити, спросить Первого Гражданина)}
{3107}{}{Купим унитазы!! Жители Модока. Дописано ножом: Чузен ты гад!!!}
{3108}{}{Купим резиновую куклу Чузена для отработки новых оружий. Гвардейцы АНКЛАВ}
{3109}{}{Куплю садовых вредитилей. Заколебал растительный юмор! Тифон}
# ** ИЩУ ** 3110..3116
{3110}{}{Пропала роба, сиреневая с желтыми полосами, просьба вернуть за вознаграждение. Хранитель моста.}
{3111}{}{Пропала кукла=85 см,с зевающим ртом,блондинка... нагая. Нашедшим просьба оставить у здания справа при входе в Модок.}
{3112}{}{Нужны брамины. Желательно взрывающиеся. Хранитель моста.}
{3113}{}{Ищем справедливость. Рэйнджеры
Ищем рэйнджеров. *Справедливость* [под перечеркнутой надписью виднеется : "Работорговцы"]}
{3114}{}{Ищем молодые таланты. Обращаться в офис в Нью-Рено *Golden Globes Porn*}
{3115}{}{Ищу свой глаз. *Капрал Диксон*}
{3116}{}{Нашедшему здоровенную металлическую задницу убедительная просиба не смеяться, никому не показывать и обязательно вернуть в ООО "Анклав"! Ф. Хорриган(верхняя часть)}
# ** ПРОДАМ ** 3117..3130
{3117}{}{Продаем нефть, оружие, лекарства, кроме того есть Гекк. Нефтяная вышка. Самовывоз. Просьба не взрывать. Ричардсон}
{3118}{}{Продам Скайнет, можно на запчасти. Chosen One.}
{3119}{}{Первое июля. 
Куплю энерго батареи для заправки тачки. Оплата по договорённости. Chosen One.

Тринадцатое июля. 
Продам трофеи. В том числе: гранаты, пистолеты, пулемёты, ружья, базуки, холодное оружие, броню, медикаменты, патроны (в том числе энеро батареи). Дёшево! (Хорошо по пустыне погулял! Блин, куда же всё это сбагрить?) Chosen One.}
{3120}{}{В связи с некоторыми геополитическими изменениями срочно продам благоустроенную нефтяную вышку с действующим атомным реактором. Президент Ричардсон.}
{3121}{}{Токсичные отходы самовывозом, по оптовым ценам. Смайли.}
{3122}{}{Продаю базу со всем ее содержимым и персоналом. Цена договорная. Для чузенов не продается. Сержант Гранит.}
{3123}{}{Продаётся Ядерный реактор (б/у) со всеми удобствами, каменная кладка, евроремонт 2143 год, цена договорная (радЭвей и Ремонтный бот прилаг.) Первый Гражданин Волт-сити. Обращаться с 8.00 до 18.00 при себе иметь Дневной пропуск}
{3124}{}{Продам гаусс-виндикатор, дорого, очень дорого. (Обращаться к Алгернону, Нью-Рено)}
{3125}{}{Продаём золотую щахту ванаминого в Рединнге. Ванаминого прилагаются. Коварный Мак Грю.}
{3126}{}{Продаю APA и лазерную винтовку. Просьба Избранному, Хорригану и Железному дровосеку не обращаться! Сержант Гранит}
{3127}{}{- Продам ГЕКК за ненадобностью оного. Избранный
- Господи, какой идиот!!! <Старейшина>}
{3128}{}{Продам часто линяющего геккона. ОЧЕНЬ дорого. Смайли.}
{3129}{}{Продам нефть. Президент.}
{3130}{}{Продаю металлолом. Дёшево. Самовывоз из Наварро.}
# ** РЕКЛАМА ** 3131..3138
{3131}{}{Спиртное крупным и мелким оптом. Семья Райт.}
{3132}{}{Гекогриль - живой грильбар в Вашем доме. Чудесное средство для быстрой зажарки любого блюда. Редкая природная разновидность геккона. Лучший рождественский подарок любимой тёще. Внимание - кормить в огнеупорном костюме. зоомагазин "старик Гекконыч"}
{3133}{}{Бесплатные споры по поводу того, кто есть Чузен. Говорящая Голова.
  <внизу начерчено> "Прием краденых камней у Головы" Чузен.}
{3134}{}{Вылечим от наркомании за 10 дней. Майрон.}
{3135}{}{У вас есть деньги? ЭТО ПОПРАВИМО! Рейдеры.}
{3136}{}{Экспресс-загар дешево, обращаться на АЭС Гекко.}
{3137}{}{Собери пять голов с татуировкой, и получи значок рейнжера. Рейнджеры НКР
 дописано: Собери пять значков рейнжеров, и получи тату на лоб. Работорговцы}
{3138}{}{Экономическое чудо. Высокоприбыльный бизнес. Новая консервная фабрика Чипа. Консервы, тушенка, печенка. Желающим заработать - просьба проходить на задний двор (в подвал, без оружия). Мутантам - специальное предложение.}
# ** УСЛУГИ ** 3139..3146
{3139}{}{Сеансы общения с духами предков. Спросить Сулика.
Общение с духами,но дешевле чем у Сулика. Хакуин.}
{3140}{}{Сеансы гаусс-терапии на дому. Ваши патроны, мой гаусс. Спросить Кейсиди.}
{3141}{}{Увлекательный морской круиз с феерическим ночным шоу! ООО "Посейдон-Трэвел"}
{3142}{}{УСЛУГИ МАГА: Снимаю порчу ломаю крушу краду взламываю. Обращаться в Гильдию Работорговцев. Кто угодно из гильдии.}
{3143}{}{Приглашаю крутых засранцев в тур по Пустоши с попутным лечением завышенной самооценки. Самый крутой засранец.}
{3144}{}{Очищу Ваш город от всего живого. *Избранный*}
{3145}{}{Пасу браминов, есть собака, опыт. Избранный}
{3146}{}{Соберу из мусора, карманной корпии, зажигалок, цветков, шприцов, ожерелий - пылесосы, тракторы, экскаваторы, рекативные самолеты, вечные двигатели первого и второго рода. Обращаться к Ретчу, НКР.}
# ** АКЦИИ ** 3147..3154
{3147}{}{Принимаем работорговцев оптом и в розницу за хорошее вознаграждение. Можно только головы. Рейнджеры НКР.}
{3148}{}{*Крупными буквами* Спешите! Спешите! Только у нас и только для вас! Аттракцион "Заржавевший анклавовец"! Разрешается стучать по лбу и пинать по заднице! Где-то в пустыне, сами найдете... Избранный.}
{3149}{}{ООО "Анклав" проводит день открытых дверей! В программе: весёлая беготня по нефтяной вышке, арм-рэслинг с Фрэнки, приседания в энергоброне, а так же экскурсия "Увидеть бомбу и умереть"! В конце программы весёлые солдаты пинками проводят вас до выхода с криками "Эвакуация!!!" ООО "Анклав"
P.S. Чузенов просьба не беспокоить.}
{3150}{}{Приглашаем на новую театральную постановку "Чужие-7"! Обращаться в Реддинг, шахту Ванаминго!}
{3151}{}{Собери 10 голов мертвяков и получи 50% скидку на гражданство Города! Линетт.}
{3152}{}{У Вас нет денег, но есть нелюбимые родственники??? Мы Вам поможем!!! За очень хорошую плату Вы можете оставить у Нас своих родственников на постоянное проживание!!! Обращаться в Дэн, Восточный район, в Гильдию Работорговцев. Метцгер.}
{3153}{}{Желающим сняться в качестве жертв в фильме "чужие" просьба почаще навещать шахту ванаминго.} 
{3154}{}{Всем пацанам из охраны Волт-Сити!!! Пэйнтболл и халявное пиво! Сбор за оградой, сами знаете где. Гражданин-сержант СТАРК}
# ** РАЗНОЕ ** 3155..3175
{3155}{}{Меняю: копье с заточенным наконечником (в неплохом состоянии) на винтовку Гауса с подробной инструкцией по эксплуатации, гарантийным талоном и прочей документацией, если таковая имеется. БЕЗ ДОПЛАТЫ. Chosen One.}
{3156}{}{Меняю двадцать шкурок золотого Гекко на обрез. Чуз.}
{3157}{}{Меняю турбоплазменную винтовку с возможностью автоматического огня на гранату Антиоха. Ну Чузен, теперь посмотрим кто из нас настоящий манчкин! Фрэнки.}
{3158}{}{Меняем чертежи ключей от вертиберда на чертежи самого вертиберда. (Обращаться в бункер Братства Стали в Сан-Франциско)}
{3159}{}{Познакомлюсь с девушкой, некурящей, непьющей, дисциплинированной, владеющей бензиновым автомобилем для извлечения взаимной выгоды. Капитан Танкера "Посейдон Ойл" Вальдез.}
{3160}{}{Розыск! Имя: Рэндэл. Кличка: Железный дровосек. Место службы: Анклав. Пропал на миссии по уничтожению Избранного. Подпись: Сержант.}
{3161}{}{Много сложной, грязной и плохооплачиваемой работы, обращаться к шрифу Реддинга.}
{3162}{}{Дайте денег, или я сейчас выброшусь! Кит.}
{3163}{}{Бюрократы Города-Уежища - №%!$ $&*$^!& (Подпись неразборчива)}
{3164}{}{Форматируем Императора. Дли Ши - бесплатно! Остальным - за $1.95}
{3165}{}{Объявление. Открылся бар "Танцующий мутант". В программе: Стриптиз в исполнении звезды пустошей мутантихи Изольды (сценический псевдоним). Живая музыка (Рок-группа "Гейгер", вокалист - Гарольд).}
{3166}{}{Поздравляю всех анклавовцев и Френка с Днём Защитника Отечества. Президент.}
{3167}{}{Обаятельная, 34 года, ищет мужчину для совместного времяпрепровождения. Интим предлагать(но втайне от мужа). Мисс Бишоп.}
{3168}{}{Познакомлюсь с порядочным мужчиной, обеспеченным с чувством юмора. Избранных просьба не беспокоить. Линнет}
{3169}{}{27 июля 2247 года ушёл из Арройо на поиски ГЭККа и не вернулся Избранный. На EMS не отвечает. Нашедшму просьба обратиться на вышку "Посейдон", третий уровень, первая камера, а также напомнить Избранному, что до gameover'а у него остался один месяц манчкинства. Старейшина, 27 июня 2260.}
{3170}{}{Нубы должны страдать! Гопы}
{3171}{}{Гопы должны страдать! Нубы}
{3172}{}{Вы, РЕАЛЬНО, ничего не понимаете в Сути Пустоши. Хабологи}
{3173}{}{!!!АТОМ ВСЕСИЛЬНО ИСКРИТ!!!!}
{3174}{}{Продам 50 томми-ганов или обменяю их на 50 патронов к .223 пистолету. Неизвестный.}
{3175}{}{Ок. Krizalis}

#
# ncr Spy mission quest. Using in q_spy_mission.fos
#

{3180}{}{МакКлюр? Вы и сегодня умудрились опоздать.}
{3181}{}{Прошу прощения, Первый Гражданин, слишком много дел. Подобное не повторится.}
{3182}{}{Вы говорите это всегда. Я бы давно от вас избавилась, но, увы, сейчас это невозможно.}
{3183}{}{Не понимаю, о чем вы, Первый Гражданин.}
{3184}{}{МакКлюр, давайте откажемся от лицемерия, когда мы наедине. Мы оба прекрасно понимаем, о чем идет речь.}
{3185}{}{Хорошо, Линетт. Я всего лишь обязан выполнить свой долг. Надеюсь, в скором будущем положение дел изменится.}
{3186}{}{А я надеюсь, что статус-кво сохранится. Ваша самоуверенность вас подведет, и вы совершите ошибку. А я ее использую.}
{3187}{}{Хотелось бы верить, что у вас не будет такого шанса. Отставим наши словесные баталии и вернемся к работе.}
{3188}{}{Слушаю вас, советник.}
{3189}{}{Настроения в Городе не изменились. За последнюю неделю не зафиксировано значимых происшествий и преступлений.}
{3190}{}{Да сам факт вашего существования, советник, является преступлением!}
{3191}{}{Первый Гражданин, мне уйти?}
{3192}{}{Ладно, забудем, мне нельзя поддаваться эмоциям. Продолжайте.}
{3193}{}{В Реддинге зафиксировано несколько случаев нападения на стражей порядка. Недовольство коренных жителей растет.}
{3194}{}{Добыча?}
{3195}{}{Темпы золотодобычи упали за последнюю неделю. Нам нужны еще шахтеры. Возможно, нам следует отправить часть слуг в шахты Реддинга.}
{3196}{}{Чепуха. Усильте подразделения регуляторов. Чтобы никто не мог отлынивать от работы. Что с НКР?}
{3197}{}{Военное положение все еще в силе. На столицу Республики было совершено несколько нападений рейдеров, они отбиты армией НКР.}
{3198}{}{Отношения армии и Братства Стали остались без изменений?}
{3199}{}{По информации из достоверных источников, Шейман пытается наладить контакт с паладинами. Но пока безрезультатно.}
{3200}{}{Что-нибудь еще?}
{3201}{}{Нет, на сегодня это все.}
{3202}{}{Отвратительно. Хотя, чего я еще могла бы ожидать от предателя?}
{3203}{}{Предлагаю обойтись без навешивания ярлыков. И вообще отказаться от поступков, о которых можно пожалеть в будущем...}
{3204}{}{Это угроза, МакКлюр? Не смешите меня. Вы свободны.}
{3205}{}{Всего доброго, Первый Гражданин.}


#
# ncr westin vs bishop quest chain. Using in ncr_smit.fos
#
# диалог на воротах города между смитом и охранником
{3400}{}{Здравствуйте. Предъявите пропуск.}
{3401}{}{Привествую, офицер. Увы, у меня нет пропуска.}
{3402}{}{В таком случае, сообщите о цели визита в НКР и представьтесь.}
{3403}{}{Меня зовут Смит. Собирался заглянуть в местный бар.}
{3404}{}{Cмит, для того, чтобы пройти в НКР, вам потребуется оформить пропуск у капитана охраны.}
{3405}{}{Где я могу найти капитана охраны?}
{3406}{}{Капитана вы найдете на таможне. Удачного дня.}
{3407}{}{Всего доброго, офицер.}
{3408}{}{Надо же! Мне крупно повезло, на входе нет охраны!}
# переговоры Смита и Бишопа по радио
{3420}{}{[Говорит в рацию] Прием. Проверка связи.}
{3421}{}{Прием. Проверка связи.}
{3422}{}{..шш..}

{3423}{}{[Говорит в рацию] Ворон, Ворон. Я Брамин, прием.}
{3424}{}{Ворон, Ворон. Я Брамин, прием.}
{3425}{}{..шш..}

{3426}{}{[Говорит в рацию] Ворон, я Брамин. Брамин вызывает Ворона.}
{3427}{}{Ворон, я Брамин. Брамин вызывает Ворона}
{3428}{}{Пошел на х..}

{3429}{}{[Говорит в рацию] Ворон, повторите, не понял, прием.}
{3430}{}{Ворон, повторите, не понял, прием.}
{3431}{}{ Пошел на х.. ..шш.. брамин ..шш.. ..ный!!!!}

{3432}{}{[Говорит в рацию] Ворон, ответьте. Почему ангелы летают?}
{3433}{}{Ворон, ответьте. Почему ангелы летают?}
{3434}{}{Ты что, совсем тупой? ..шш.. Пошел ты в ..шш.. кретин! Я тебя.. ..шш... и твою мать.. ..шш.. и твоего отца.. ..шш.. Ты меня понял, жо.. ..шш. .шами?! Прием?!}

{3435}{}{Похоже, я выбрал не ту волну. [Настраивает рацию и повторяет] Ворон, прием, я Брамин.}
{3436}{}{Ворон, прием, я Брамин.}
{3437}{}{ Слышу тебя, Брамин. Я Ворон. Прием. }

{3438}{}{Ну вот, слава богу. [Говорит в рацию] Ворон, почему ангелы летают? }
{3439}{}{Ворон, почему ангелы летают?}
{3440}{}{Смит, браминья твоя башка. Как ты задрал со своей конспирацией, придурок. Как понял меня, прием?}

{3441}{}{[Про себя] Отзыв правильный. Отлично. [В рацию] Прошу прощения, мистер Бишоп.}
{3442}{}{Прошу прощения, мистер Бишоп.}
{3443}{}{Как поживает Вейстин? Какие новости?}

{3444}{}{[В рацию] Я в НКР, мистер Бишоп. Вейстин на прицеле. В ближайшие дни приступаю к нейтрализации советника.}
{3445}{}{Я в НКР, мистер Бишоп. Вейстин на прицеле. В ближайшие дни приступаю к нейтрализации советника.}
{3446}{}{Не тяни, Смит. Иначе я буду вынужден найти кого-то другого для этой работы. А тобой займутся мои люди.}

{3447}{}{[В рацию] Нет проблем, мистер Бишоп. Можете не беспокоиться на счет советника.}
{3448}{}{Нет проблем, мистер Бишоп. Можете не беспокоиться на счет советника.}
{3449}{}{ Я тебя предупредил. Конец связи. }

{3450}{}{[В рацию] Конец связи.}
{3451}{}{Конец связи.}
#Если грант мертв или нет в радиусе поиска
{3455}{}{Ха. Грант куда-то отлучился. То, что мне нужно.}
# Грант заметил Смита
{3456}{}{Эй! Кто здесь! Выйди на свет, иначе стреляю!}
{3457}{}{Что случилось? Я не делаю ничего противозаконного.}
{3458}{}{Здесь находиться запрещено. Проваливай, пока цел.}
{3459}{}{Уже ухожу, прошу прощения.}
#Диалог Смита и Вейстина
{3460}{}{Здравствуйте, мистер Вейстин.}
{3461}{}{Что... Кто вы? Как вы оказались в моем доме?! Охрана! На помощь!}
{3462}{}{Никто не придет, мистер Вейстин. Я здесь, чтобы передать вам привет от господина Бишопа.}
{3463}{}{Бишоп? Человек Бишопа?! Вы пришли меня убить?!}
{3464}{}{Удивительная проницательность. Прощайте, мистер Вейстин.}
{3465}{}{Помогите! Убивают!}
#Вейстина нет на месте или он убит
{3466}{}{Черт подери! Вейстина нет на месте! Проклятье.}

#Ill brahmin felix quest. Using in ncr_common.fos
{3470}{}{Вы на самом деле готовы проверить, чем отравился брамин, используя резиновые перчатки и вантус?}
{3471}{}{Да, с богом!}
{3472}{}{НИ ЗА ЧТО!!!}
{3473}{}{Ух, дрянь какая! После нескольких унизительных мгновений вы извлекаете наружу причину "отравления" брамина.}
{3474}{}{Вы нашли @lex item_name@. И как только он мог ЭТО сожрать...}
{3475}{}{Вы кладете непонятный цветок Феликса под морду брамина. Он с интересом на него смотрит, и с громким чавканьем съедает. Смотрит на вас с надеждой: а еще есть?}

# Quest "Arroyo defence". Using in scripts arroyo_mynoc_defence.fos & map_arroyo_rayders_camp.fos
{3480}{}{Вы получили @lex exp@ опыта.}
{3481}{}{Вы отстали от группы.}
{3482}{}{Вы обнаружили рейдеров нападающих на караваны Арройо.}
{3483}{}{Вы не успели расправиться с рейдерами, они сбежали.}

#caravan quest.Using in caravan.fos
{3500}{}{Немедленно отойди от груза}
{3500}{}{Эй! А ну-ка, отвали от повозок}
{3500}{}{Не вздумай приближаться к грузу}
{3500}{}{Убирайся, не смей к ним прикасаться}
{3500}{}{Отойди. Быстро}
{3500}{}{Не трогай}


#hub holodisk quest. Using in loc_tech_bunker.fos
{3600}{}{Вы не можете иметь больше таких предметов.}


# Resources system
{3700}{}{Здесь больше делать нечего}
{3701}{}{Вы не можете взять больше}
{3702}{}{Вы добыли : @lex itemname@ - @lex count@@lex type@}
{3703}{}{Вы добыли : @lex itemname@}
{3704}{}{Вы добыли немного дров}
{3705}{}{шт}
{3706}{}{кг}

# SF Invasion mobs. Using in sf_invasion.fos
{5100}{}{Расправляет крылья}
{5100}{}{ж-ж-ж}
{5100}{}{Шелестит крыльями}
{5100}{}{Щелк! Щелк!}
{5100}{}{Шёлкает}
{5100}{}{Угрожающе шевелит жвалами}
{5100}{}{Громко щелкает}
{5100}{}{Поворачивает голову в вашу сторону и издает какой-то скрежет}
{5101}{}{Прислушивается к собрату}
{5101}{}{Останавливается и готовится напасть}
{5101}{}{Медленно разворачивается и замирает}

# Квест Нэнси и Сид. Using in sf_common.fos
{5110}{}{S.O.S.}
{5111}{}{Это Нэнси... Сид, он...}
{5112}{}{Помогите кто-нибудь, я в палатке наркодилеров на побережье... Ранена... Умираю... Сид ушел...}

#Квест "Непыльная работа". navarro.fos
{5150}{}{Вы сканируете память робота с помощью сканера. Объем сохраненных данных: @lex value@%}
{5151}{}{Вы сканируете память робота с помощью сканера. Объем сохраненных данных: 100%! Можно возвращаться к технику в Наварро.}
{5152}{}{Банк данных этого робота опустошен. Возможно, кто-то уже просканировал и разрушил его память.}
{5153}{}{Вы устанавливаете чип в коммуникационный разъем робота. Остается только привести его в работоспособное состояние, и у вас будет самый лучший телохранитель.}
{5154}{}{Вам понятия не имеете, где этот разъем и как использовать чип.}
{5155}{}{Вам не удалось отремонтировать робота-стража.}
{5156}{}{Используя накопленные знания, вы приводите стража в работоспособное состояние. Теперь он станет вашим спутником.}

# Сообщения и тексты на карте Рынка. Using in map_barter_ground.fos
{5200}{}{Эй! @lex pname@! Ты зря захватил это с собой! К нам нельзя приносить эту дрянь!}
{5200}{}{Запрещенный предмет! Запрещенный предмет! Уничтожить @lex pname@}
{5200}{}{Внимание, всем! У репликанта @lex pname@ замечены запрещенные предметы. Уничтожить!}

# Урон от энерогетических барьеров
{5300}{}{You are shocked by the weakened force field.}
{5301}{}{You are shocked by the force field.}
{5302}{}{You fail to lower the force field.}
{5303}{}{You disable the force field.}
{5304}{}{You enable the force field.}
{5305}{}{You destroy the force field emitter.}
{5306}{}{You can see no way to use the emitter.}
{5307}{}{You can see no way to use the force field.}
{5308}{}{Yes, there is a lot of energy going through there. You stop before the electricity arcs to your hand.}
{5309}{}{You fail to do anything useful, and take about 50,000 volts for it. At least you won't have to worry about shaving.}
{5310}{}{The force field seems to be unaffected.}
{5311}{}{You fail to upper the force field.}

# Охрана на воротах реддинга. redd_gates.fos
{5400}{}{Назад, немедленно!@@Не подходи к двери @lex pname@. Второй раз предупреждать не буду.}
{5401}{}{Ты слишком глуп@lex sex@. Эта ошибка будет стоить тебе жизни!@@Тебя предупреждали}
{5402}{}{КУДА ТЫ? ТЫ ТРУП@@Нарушитель. Огонь на поражение}

# Работа в шахте Реддинга. redd_mines.fos
{5420}{}{Вы бережно опускаете один из золотых самородков в вагонетку. Всего добыто золота: @lex num@.}

#Могила мужа Руни
{5425}{}{Да, это та самая могила. Вы оставляете цветы возле обелиска.}

# Сообщение на входе в Реддинг
{5430}{}{По приближению к городу, Вы замечаете, что северная его часть огорожена длинной стеной.}

# Город из ГЕККа map_geck_city.fos
{5500}{}{This place is completely unsuitable for contructing a city.}
{5501}{}{Wrong code. Activation cancelled.}
{5502}{}{Code accepted. Activating G.E.C.K...}
{5503}{}{Citizen's info saved. Name: @lex pname@.}
{5504}{}{Congratulations! You have been registered in city's system. You now have an access to all the systems.}
{5505}{}{Garden of Eden Construction Kit work is now complete... Welcome to city that G.E.C.K. built.}
{5506}{}{Электронный замок на этой двери невозможно открыть стандартными способами. От отмычек или динамита не будет никакого толку.}
{5507}{}{@lex leadername@ has entered you into the lists of citizens of city constructed by G.E.C.K.}
{5508}{}{@lex leadername@ has removed you from the the lists of citizens of city constructed by G.E.C.K.}
{5509}{}{Generator is charged, total charges: @lex charges@. Estimated barrier work time: @lex time@.}
{5510}{}{Out of order.}
{5511}{}{Посмотрим, что здесь можно сделать...}

#Квест "Семья", ГУ, Вэлери. vcity_common.fos
{5800}{}{Типичная женская писанина. Даже смотреть не хочется.}
{5801}{}{Вам совершенно случайно попадаются на глаза первые строки письма. Они настолько увлекают вас, что вы дочитываете до самого конца: …и прости, что я так вела себя с тобой. Нас ведь осталось только двое во всём мире. Надеюсь и хочу увидеть тебя. Любящая тебя дочь.}
{5802}{}{[…надо же. Написано просто кровью сердца. Вы еще раз  перечитываете  письмо, и  оно остается у вас в памяти].}

# Квест "Свет мой, зеркальце", ГУ, Доктор Хелен Трой. vcity_common.fos
{5805}{}{Ну и заумь. Совершенно ничего непонятно.}
{5806}{}{Да тут не так уж и сложно всё. Любой осёл разберется. Вы запоминаете содержимое.}

#Квест "Рога Изобилия", БХ, Начальник фабрики. broken_common.fos
{5900}{}{Убито саботажников по заданию АХС-7: @lex dead@ из 40.}
{5901}{}{В глазах рябит от формул и чертежей. Пускай специалисты разбираются.}
{5902}{}{Описание технологии обогащения, изложенное четким  языком, со множеством прекрасных чертежей. Вы с удовольствием вникаете в суть дела.}

#Квест "Возвращение ребенка"
{5905}{}{Проваливай отсюда, извращенец.@@Посмотрите на эту мразь! Он набрался наглости вернуться сюда!@@таким как ты в польше химическую кастрацию делают, @Иди в жопу извращенец!@И откуда вы, мрази, беретесь.@@Охотники уже идут за тобой. Ты сдохнешь!}

# Квест "Гвардия Города-Убежища. Испытание первое". fighter_quest.fos
{5910}{}{Начат поединок c @lex npcname@. Удачи!}
{5911}{}{Вы победили в поединке с @lex npcname@. Поздравляем. Прекратите атаку, иначе вас не поймут окружающие.}
{5912}{}{Удача была не на вашей стороне. Вы проиграли поединок с @lex npcname@.}
{5913}{}{В результате поединка ваш противник был убит.}
{5914}{}{Жулик! Договаривались без оружия!}

#Квест "Гвардия Города-Убежища. Испытание третье". vc_guardsman.fos
{5915}{}{Вы в правильной позиции. Оставайтесь на месте до первой команды. Равнение на середину!}
{5916}{}{Да сколько можно? Стать в строй, черт тебя дери! Иначе отправлю к мамочке!}
{5917}{}{Вы что-то сделали не так. Задание провалено.}


#Монологи-песни Илая. eli.fos
#4
{5960}{}{Да, сегодня позволено все,}
{5961}{}{Что крушишь себя так увлеченно.}
{5962}{}{Видишь, я над тобою кружу.}
{5963}{}{Это я фиолетово-черный.}
{5964}{}{Если можешь, беги, рассекая круги,}
{5965}{}{Только чувствуй себя обреченной.}
{5966}{}{Стоит солнцу зайти, вот и я}
{5967}{}{Стану вмиг фиолетово-черным.}

#Квест "Ночь нежна." Модок. map_modoc.fos
{5970}{}{От зараза, охранника поставили. Надо сваливать от греха…}
{5971}{}{Отличное место для наблюдений. Осталось дождаться ночи и выяснить, что происходит с браминами.}
{5972}{}{Не стреляй, человек. Давай поговорим!}

#Монологи-песни Илая. eli.fos
#1
{5973}{}{Я сам себе и небо и луна}
{5974}{}{Голая, довольная луна}
{5975}{}{Долгая дорога, да и то не моя.}
{5976}{}{За мною зажигали города}
{5977}{}{Глупые чужие города}
{5978}{}{Там меня любили, только это не я.}
#2
{5980}{}{Мертвая змея не шипит}
{5981}{}{Не щебечет дохлый щегол}
{5982}{}{Мертвый негр не идет играть в баскетбол...}
{5983}{}{Только мертвый негр не идет играть в баскетбол...}
{5984}{}{Ай-я-я-я-я-я-яй убили негра, убили негра, убили...}
{5985}{}{Ай-я-я-я-я-яй ни за что ни про что...суки замочили...}
{5986}{}{Ай-я-я-я-я-я-яй убили негра, убили негра, убили...}
{5987}{}{Ай-я-я-я-я-яй ни за что ни про что...суки замочили...}
#3
{5988}{}{Я на чердаке лежу у себя на дому.}
{5989}{}{Мне скучно до зарезу Бог знает почему.} 
{5990}{}{Вдруг слышу за собою совы нежные "У-юй" -}
{5991}{}{У меня на душе стало веселее,}
{5992}{}{А-лай-лай-лай, стало веселее.} 
{5993}{}{Я по дороге иду к другу-разбойнику,} 
{5994}{}{Мне тоскливо одному в незнакомом краю.} 
{5995}{}{Вдруг слышу за собою совы нежные "У-юй" -}
{5996}{}{У меня на душе стало веселее,}
{5997}{}{А-лай-лай-лай, стало веселее.}


# Основной сюжетный квест. Резерв 6000...7000
{6000}{}{В вашем ПипБое записана важная информация.}

# Сражения, поединки. battle_info.fos
{7001}{}{Невозможно использовать. Возможно, нужно дождаться следующего этапа сражения.}
{7002}{}{Невозможно использовать. Доступ только для участников сражения.}
{7003}{}{Невозможно использовать. Доступ только для победителей.}

# ГУ, квестовая линия поддержки Линетт. vc_lynett.fos
{7100}{}{Вот сука черномазая, говорила – легкая мишень… }
{7101}{}{Ха, как эта черная сука и обещала – раз плюнуть…}

# Специальные Энкаунтеры. 70000...70100
# Переводчику: большую часть английских текстов для них можно скопировать из оригинала. Т.е. нужно.

# Портал Хранителя
{70000}{}{Вы сломали водяной чип в убежище. Вам почему-то кажется что в течении 100-150ти дней в убежище кончится вся вода. Скорее всего жители убежища будут обеспокоены этим.}
{70001}{}{*Биип*@@*Бип* Би-оп*@@*Биоп*}

#Говорящая голова.
{70002}{}{Чо--?}
{70003}{}{УБЕРИ СВОИ ГРЯЗНЫЕ РУКИ ОТ МЕНЯ!}
{70004}{}{*Гм*}
{70005}{}{КТО ПОЗВОЛЯЛ ПРИБЛИЖАТСЯ К СВЯЩЕННОЙ ГОЛОВЕ ЖИТЕЛЯ УБЕЖИЩА?!}
{70006}{}{Это я, Избранный.} 
{70007}{}{ХА-ХА-ХА-ХА-ХА}
{70008}{}{*Ты*!? Избранный?}
{70009}{}{ТЫ НЕ БОЛЬШЕ ЧЕМ МОЙ ПАЛЕЦ!}
{70010}{}{ТЫ *НЕ* ИЗБРАННЫЙ!}
{70011}{}{Да, я Избранный.}
{70012}{}{Нет.}
{70013}{}{Да.}
{70014}{}{УХ-УХ.}
{70015}{}{УХ-ХУХ.}
{70016}{}{УХ-УХ.}
{70017}{}{УХ-ХУХ.}
# Спустя 12 часов.
{70018}{}{УХ...УХ...}
{70019}{}{УХ...ХУХ...}
{70020}{}{УХ...ХВАТИТ ЭТОГО!}
{70021}{}{ОЧЕНЬ ХОРОШО, ТЫ ДОКАЗАЛ ЭТО!}
{70022}{}{ТЫ *ДЕЙСТВИТЕЛЬНО* ИЗБРАННЫЙ!}
{70023}{}{ВОЗЬМИ ЭТО.}
{70024}{}{ТЕПЕРЬ ОСТАВЬ МЕНЯ В ПОКОЕ.}
{70025}{}{Спасибо!}
{70026}{}{ДА, ЧТО УГОДНО.А ТЕПЕРЬ УБИРАЙСЯ!}
{70027}{}{ПРОКЛЯТЫЕ ТУРИСТЫ!}
{70028}{}{Спустя 12 часа}
{70029}{}{!!!ЧТО?! УКРАСТЬ У МЕНЯ!? И ТЫ ЭТО СДЕЛАЕШЬ?!!!} 

# Железный дровосек
{70050}{}{Масло.} 

# Склад пончиков
{70060}{}{Эту стелу воздвигли друзья и знакомые Пончика в знак любви и уважения. Ниже нацарапано гвоздем: враки, это он сам сделал (друзья и знакомые).} 

